/**
 * Mastercard Ezaccess For Issuers API
 * [![](https://mstr.cd/320oUJL)](https://developer.mastercard.com)  This is the Mastercard EzAccess for Issuers API.  This API uses OAuth 1.0a for authenticating client applications. For that, please refer to [Using OAuth 1.0a to Access Mastercard APIs](https://mstr.cd/31YcrTi).  The transport between client applications and Mastercard EzAccess service is secured using [TLS/SSL](https://w.wiki/PoA).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Card', 'model/EnrolledCardAllOf'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Card'), require('./EnrolledCardAllOf'));
  } else {
    // Browser globals (root is window)
    if (!root.MastercardEzaccessForIssuersApi) {
      root.MastercardEzaccessForIssuersApi = {};
    }
    root.MastercardEzaccessForIssuersApi.EnrolledCard = factory(root.MastercardEzaccessForIssuersApi.ApiClient, root.MastercardEzaccessForIssuersApi.Card, root.MastercardEzaccessForIssuersApi.EnrolledCardAllOf);
  }
}(this, function(ApiClient, Card, EnrolledCardAllOf) {
  'use strict';



  /**
   * The EnrolledCard model module.
   * @module model/EnrolledCard
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>EnrolledCard</code>.
   * @alias module:model/EnrolledCard
   * @class
   * @implements module:model/Card
   * @implements module:model/EnrolledCardAllOf
   */
  var exports = function() {
    var _this = this;

    Card.call(_this);
    EnrolledCardAllOf.call(_this);
  };

  /**
   * Constructs a <code>EnrolledCard</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EnrolledCard} obj Optional instance to populate.
   * @return {module:model/EnrolledCard} The populated <code>EnrolledCard</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      Card.constructFromObject(data, obj);
      EnrolledCardAllOf.constructFromObject(data, obj);
      if (data.hasOwnProperty('last4Digits')) {
        obj['last4Digits'] = ApiClient.convertToType(data['last4Digits'], 'Number');
      }
      if (data.hasOwnProperty('eaid')) {
        obj['eaid'] = ApiClient.convertToType(data['eaid'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * The last 4 digits of a card PAN.
   * @member {Number} last4Digits
   */
  exports.prototype['last4Digits'] = undefined;
  /**
   * The 16-digit Mastercard EzAccess ID (EAID) of the card.
   * @member {String} eaid
   */
  exports.prototype['eaid'] = undefined;
  /**
   * Status of the card. Acceptable values are: ACTIVE, BLOCKED
   * @member {String} status
   */
  exports.prototype['status'] = undefined;

  // Implement Card interface:
  /**
   * The last 4 digits of a card PAN.
   * @member {Number} last4Digits
   */
exports.prototype['last4Digits'] = undefined;

  /**
   * The 16-digit Mastercard EzAccess ID (EAID) of the card.
   * @member {String} eaid
   */
exports.prototype['eaid'] = undefined;

  // Implement EnrolledCardAllOf interface:
  /**
   * Status of the card. Acceptable values are: ACTIVE, BLOCKED
   * @member {String} status
   */
exports.prototype['status'] = undefined;



  return exports;
}));


