name: Sonar
'on':
  push:
    branches:
      - "**"
  pull_request_target:
    branches:
      - "**"
    types: [opened, synchronize, reopened, labeled]
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for external PR
        if: ${{ !(contains(github.event.pull_request.labels.*.name, 'safe') ||
          github.event.pull_request.head.repo.full_name == github.repository ||
          github.event_name != 'pull_request_target') }}
        run: echo "Unsecure PR, must be labelled with the 'safe' label, then run the workflow again" && exit 1
      - name: Use Node.js 16.10.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.10.0
      - name: Build with npm
        run: |
          npm ci
          npm run build --if-present
          npm test --no-watch --code-coverage
          npm run
      - name: SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
        with:
          args: >
            -Dsonar.organization=mastercard
            -Dsonar.projectName=Mastercard_city-key-ezaccess-reference-app
            -Dsonar.projectKey=Mastercard_city-key-ezaccess-reference-app
            -Dsonar.tests=./reference-app/src
            -Dsonar.typescript.lcov.reportPaths=./reference-app/coverage/report-lcov/lcov.info
            -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=${{
            secrets.SONAR_TOKEN }}